import { StyleSheet, Platform } from 'react-native';

const FONT_BOLD = Platform.OS === 'android' ? 'Gilroy-Bold' : 'Poppins-Bold';
const FONT_SEMIBOLD = Platform.OS === 'android' ? 'Gilroy-SemiBold' : 'Poppins-SemiBold';
const FONT_MEDIUM = Platform.OS === 'android' ? 'Gilroy-Medium' : 'Poppins-Medium';
const FONT_REGULAR = Platform.OS === 'android' ? 'Gilroy-Regular' : 'Poppins-Regular';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 6, // Flush with bottom tab bar per Add User specification
  },

  // ===== TOP PERSONAL GREETING HERO =====
  heroGreetingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  heroLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  avatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F5F3FF',
    borderWidth: 1.5,
    borderColor: '#DDD6FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#6B46C1',
    fontFamily: FONT_BOLD,
  },
  greetingCol: {
    flex: 1,
  },
  greetingSalute: {
    fontSize: 12,
    color: '#64748B',
    fontFamily: FONT_MEDIUM,
  },
  greetingName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
    marginTop: 1,
  },
  heroDateSub: {
    fontSize: 11,
    color: '#94A3B8',
    fontFamily: FONT_REGULAR,
    marginTop: 1,
  },
  heroRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  orgPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F5F3FF',
    borderWidth: 1,
    borderColor: '#DDD6FE',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  orgPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6B46C1',
    fontFamily: FONT_BOLD,
    maxWidth: 130,
  },

  // ===== 1. BRANCH CASH VAULT CARD =====
  vaultCard: {
    backgroundColor: '#F3F4F6', // Gray card
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 16,
    marginTop: 6,
    marginBottom: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  vaultTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  vaultLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  vaultLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 0.6,
    fontFamily: FONT_BOLD,
  },
  vaultAmount: {
    fontSize: 26,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
  },
  vaultSub: {
    fontSize: 11,
    color: '#059669',
    marginTop: 3,
    fontWeight: '600',
    fontFamily: FONT_MEDIUM,
  },
  vaultActionBtns: {
    flexDirection: 'row',
    gap: 8,
  },
  btnInject: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
  },
  btnInjectText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#059669',
    fontFamily: FONT_BOLD,
  },
  btnExpense: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
  },
  btnExpenseText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#DC2626',
    fontFamily: FONT_BOLD,
  },
  settlementBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  settlementLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  settlementText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#334155',
    fontFamily: FONT_MEDIUM,
  },
  settlementArrow: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B46C1',
    fontFamily: FONT_BOLD,
  },

  // ===== 2. REALIZED PROFIT POOL CARD =====
  profitPoolCard: {
    backgroundColor: '#F3F4F6', // Gray card
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 16,
    marginBottom: 14,
  },
  profitTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  profitLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6B46C1',
    letterSpacing: 0.5,
    fontFamily: FONT_BOLD,
  },
  profitAmount: {
    fontSize: 22,
    fontWeight: '800',
    color: '#581C87',
    fontFamily: FONT_BOLD,
    marginTop: 2,
  },
  profitSub: {
    fontSize: 11,
    color: '#7E22CE',
    marginTop: 2,
    fontFamily: FONT_REGULAR,
  },
  contractedBadge: {
    alignItems: 'flex-end',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E9D5FF',
  },
  contractedLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#6B7280',
    fontFamily: FONT_BOLD,
  },
  contractedVal: {
    fontSize: 12,
    fontWeight: '800',
    color: '#059669',
    fontFamily: FONT_BOLD,
    marginTop: 1,
  },
  profitBtnRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  btnReinvest: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#6B46C1',
    paddingVertical: 10,
    borderRadius: 10,
  },
  btnReinvestText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: FONT_BOLD,
  },
  btnWithdraw: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#6B46C1',
    paddingVertical: 10,
    borderRadius: 10,
  },
  btnWithdrawText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B46C1',
    fontFamily: FONT_BOLD,
  },

  // ===== 3. QUICK ACTIONS GRID =====
  actionSection: {
    marginBottom: 14,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionCard: {
    width: '48.5%',
    backgroundColor: '#F3F4F6', // Gray card
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  actionIconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
  },
  actionSublabel: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 1,
    fontFamily: FONT_REGULAR,
  },

  // ===== 4. SECTION HEADERS =====
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1E293B',
    fontFamily: FONT_BOLD,
  },
  sectionActionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B46C1',
    fontFamily: FONT_BOLD,
  },

  // ===== 5. 2x2 PORTFOLIO METRICS =====
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  metricCard: {
    width: '48.5%',
    backgroundColor: '#F3F4F6', // Gray card
    borderRadius: 14,
    padding: 12,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  metricTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 0.4,
    fontFamily: FONT_BOLD,
  },
  metricIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricValue: {
    fontSize: 17,
    fontWeight: '800',
    marginTop: 2,
    fontFamily: FONT_BOLD,
  },
  metricSub: {
    fontSize: 10,
    color: '#64748B',
    marginTop: 3,
    fontFamily: FONT_MEDIUM,
  },

  // ===== 6. TODAY RECOVERY TARGET =====
  todayCard: {
    backgroundColor: '#F3F4F6', // Gray card
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 14,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  todayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  todayTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
  },
  todaySubtitle: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 1,
    fontFamily: FONT_REGULAR,
  },
  todayBadge: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  todayBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
    fontFamily: FONT_BOLD,
  },
  todayProgressTrack: {
    height: 7,
    backgroundColor: '#F1F5F9',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 10,
  },
  todayProgressFill: {
    height: '100%',
    backgroundColor: '#059669',
    borderRadius: 4,
  },
  todayStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  todayStatLabel: {
    fontSize: 10,
    color: '#64748B',
    fontFamily: FONT_MEDIUM,
  },
  todayStatVal: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 2,
    fontFamily: FONT_BOLD,
  },

  // ===== 7. DUE TODAY LIST =====
  dueList: {
    gap: 8,
    marginBottom: 10,
  },
  emptyDueCard: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  emptyDueText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#059669',
    fontFamily: FONT_MEDIUM,
  },
  dueCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F3F4F6', // Gray card
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  dueLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  dueAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DDD6FE',
  },
  dueAvatarText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#6B46C1',
    fontFamily: FONT_BOLD,
  },
  dueBorrowerName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
  },
  dueLoanSub: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
    fontFamily: FONT_MEDIUM,
  },
  dueRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  dueAmount: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
  },
  btnQuickCollect: {
    backgroundColor: '#6B46C1',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  btnQuickCollectText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: FONT_BOLD,
  },

  // ===== SKELETON PLACEHOLDERS =====
  skeletonContainer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    gap: 14,
  },
  skeletonGreetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  skeletonGreetingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  skeletonCard: {
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 16,
    gap: 12,
  },
  skeletonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  skeletonGridItem: {
    width: '48.5%',
    backgroundColor: '#F3F4F6',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 14,
    gap: 8,
  },

  // ===== MODAL STYLES =====
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: '100%',
    maxWidth: 420,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 14,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: FONT_BOLD,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 6,
    fontFamily: FONT_BOLD,
  },
  textInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#0F172A',
    fontFamily: FONT_MEDIUM,
  },
  modalBtnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#6B46C1',
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
  },
  modalBtnPrimaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: FONT_BOLD,
  },
  sourceSelectorRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  sourceChip: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceChipActive: {
    backgroundColor: '#F5F3FF',
    borderColor: '#6B46C1',
  },
  sourceChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    fontFamily: FONT_MEDIUM,
  },
  sourceChipTextActive: {
    color: '#6B46C1',
    fontWeight: '700',
    fontFamily: FONT_BOLD,
  },
});
