import { StyleSheet } from 'react-native';
import Colors from '../../../../theme/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.offWhite,
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  gridItem: {
    width: '48.5%',
  },
  actionSection: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.gray800,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionCard: {
    width: '48.5%',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    gap: 8,
  },
  actionIconBox: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.gray800,
    textAlign: 'center',
  },
  todayCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    padding: 14,
    marginBottom: 14,
  },
  todayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  todayTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.gray800,
  },
  todaySubtitle: {
    fontSize: 10,
    color: Colors.gray200,
    marginTop: 1,
  },
  todayBadge: {
    backgroundColor: Colors.successBg,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  todayBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: Colors.success,
  },
  todayProgressTrack: {
    height: 8,
    backgroundColor: Colors.lightGray200,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 12,
  },
  todayProgressFill: {
    height: '100%',
    backgroundColor: Colors.success,
    borderRadius: 4,
  },
  todayStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  todayStatLabel: {
    fontSize: 10,
    color: Colors.gray200,
    fontWeight: '600',
  },
  todayStatVal: {
    fontSize: 15,
    fontWeight: '900',
    color: Colors.gray800,
    marginTop: 2,
  },
  dueList: {
    gap: 8,
  },
  emptyDueCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    borderRadius: 10,
    padding: 16,
    alignItems: 'center',
  },
  emptyDueText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.success,
  },
  dueCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    borderRadius: 10,
    padding: 10,
  },
  dueLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  dueAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dueAvatarText: {
    fontSize: 13,
    fontWeight: '800',
    color: Colors.secondaryBlue,
  },
  dueBorrowerName: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.gray800,
  },
  dueLoanSub: {
    fontSize: 10,
    color: Colors.gray200,
    marginTop: 1,
  },
  dueRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  dueAmount: {
    fontSize: 13,
    fontWeight: '900',
    color: Colors.gray800,
  },
  btnQuickCollect: {
    backgroundColor: Colors.success,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  btnQuickCollectText: {
    fontSize: 10,
    fontWeight: '800',
    color: Colors.white,
  },
  vaultCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    padding: 14,
    marginBottom: 14,
  },
  vaultTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  vaultTitle: {
    fontSize: 9,
    fontWeight: '800',
    color: Colors.gray200,
    letterSpacing: 0.6,
  },
  vaultAmount: {
    fontSize: 22,
    fontWeight: '900',
    color: Colors.gray800,
    marginTop: 2,
  },
  vaultSub: {
    fontSize: 10,
    color: Colors.gray100,
    marginTop: 1,
  },
  vaultBtnCol: {
    flexDirection: 'row',
    gap: 6,
  },
  btnInject: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.successBg,
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
  },
  btnInjectText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.success,
  },
  btnExpense: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.errorBg,
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
  },
  btnExpenseText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.errorDanger,
  },
  settlementBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.lightGray50,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
  },
  settlementLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  settlementText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.gray800,
  },
  settlementArrow: {
    fontSize: 11,
    fontWeight: '800',
    color: Colors.secondaryBlue,
  },
});
