import { StyleSheet } from 'react-native';
import Colors from '../../../theme/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  scrollContent: {
    padding: 24,
    flexGrow: 1,
    justifyContent: 'center',
  },
  brandHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  brandLogoCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.purpleTintLightest,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.purpleBorderLight,
  },
  brandTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: Colors.gray850,
    letterSpacing: -0.5,
  },
  brandSubtitle: {
    fontSize: 13,
    color: Colors.gray200,
    marginTop: 4,
  },
  decorativeLine: {
    width: 40,
    height: 3,
    backgroundColor: Colors.secondaryBlue,
    borderRadius: 2,
    marginTop: 8,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    marginBottom: 20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeading: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.gray850,
  },
  cardSub: {
    fontSize: 13,
    color: Colors.gray200,
    marginTop: 2,
    marginBottom: 16,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.errorBg,
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 14,
  },
  errorText: {
    fontSize: 12,
    color: Colors.errorIcon,
    fontWeight: '600',
    flex: 1,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.gray350,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  inputIconBox: {
    width: 42,
    height: 46,
    backgroundColor: Colors.lightGray50,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    borderRightWidth: 0,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    flex: 1,
    height: 46,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    paddingHorizontal: 12,
    fontSize: 14,
    color: Colors.gray750,
  },
  eyeBtn: {
    position: 'absolute',
    right: 12,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  submitButton: {
    backgroundColor: Colors.secondaryBlue,
    borderRadius: 16,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    shadowColor: Colors.secondaryBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  submitText: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.white,
  },
  quickSection: {
    marginBottom: 16,
  },
  quickHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.gray800,
    letterSpacing: 0.6,
  },
  quickSub: {
    fontSize: 11,
    color: Colors.gray200,
    marginTop: 2,
    marginBottom: 10,
  },
  demoList: {
    gap: 8,
  },
  demoCard: {
    borderRadius: 14,
    borderWidth: 1.5,
    padding: 12,
  },
  demoTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  roleTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  roleIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  demoRoleTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  selectedPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  selectedPillText: {
    fontSize: 9,
    fontWeight: '900',
    color: Colors.white,
  },
  demoMeta: {
    fontSize: 11,
    color: Colors.gray200,
    marginTop: 2,
  },
  demoHighlight: {
    fontWeight: '700',
    color: Colors.gray800,
  },
  demoDesc: {
    fontSize: 10,
    color: Colors.gray100,
    marginTop: 2,
  },
  footer: {
    alignItems: 'center',
    marginTop: 12,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  footerText: {
    fontSize: 11,
    color: Colors.gray200,
    fontWeight: '500',
  },
});
