import { 
  User, Customer, LoanProduct, Loan, FundAccount, 
  FundTransaction, Expense, LoanEligibility, Reconciliation, Payment
} from '../types';

export const initialUsers: User[] = [
  { id: 1, name: 'Rajesh Kumar', phone: '9999999999', email: 'admin@fundlending.com', role: 'SUPER_ADMIN', status: 'ACTIVE' },
  { id: 2, name: 'Priya Sharma', phone: '9888888881', email: 'manager@fundlending.com', role: 'LOAN_MANAGER', status: 'ACTIVE' },
  { id: 3, name: 'Vikram Singh', phone: '9777777772', email: 'vikram.collector@fundlending.com', role: 'COLLECTOR', status: 'ACTIVE' },
  { id: 4, name: 'Anjali Gupta', phone: '9666666663', email: 'accountant@fundlending.com', role: 'ACCOUNTANT', status: 'ACTIVE' },
];

export const initialFundAccounts: FundAccount[] = [
  { id: 1, account_code: 'CASH_MAIN', account_name: 'Main Cash Wallet (Physical Field Cash)', account_type: 'CASH', balance: 145000 },
  { id: 2, account_code: 'BANK_MAIN', account_name: 'Primary Business Current Account', account_type: 'BANK', balance: 380000 },
  { id: 3, account_code: 'UPI_MAIN', account_name: 'Merchant UPI Collection Account', account_type: 'UPI', balance: 75000 },
];

export const initialLoanProducts: LoanProduct[] = [
  {
    id: 1,
    product_code: 'WEEKLY_STANDARD',
    product_name: 'Weekly Loan - Common Customers',
    customer_type: 'COMMON_CUSTOMER',
    repayment_frequency: 'WEEKLY',
    description: '10-week installment cycle for households and salaried individuals with fixed flat interest.',
    default_installments: 10,
    default_income_value: 0.20, // 20% income
    income_type: 'PERCENTAGE',
  },
  {
    id: 2,
    product_code: 'DAILY_SHOP',
    product_name: 'Daily Loan - Shopkeepers',
    customer_type: 'SHOPKEEPER',
    repayment_frequency: 'DAILY',
    description: '25-day rapid turnover micro-capital for retail shops, grocery, and local merchants.',
    default_installments: 25,
    default_income_value: 2000, // Fixed ₹2,000 fee
    income_type: 'FIXED_FEE',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 101,
    customer_code: 'CUST-SK-001',
    full_name: 'Ramesh Patel',
    phone: '9820112233',
    alternate_phone: '9820112234',
    address: 'Shop 14, Main Market, MG Road',
    city: 'Ahmedabad',
    customer_type: 'SHOPKEEPER',
    shop_name: 'Patel Provision & Kirana Store',
    status: 'ACTIVE',
    registration_date: '2026-01-10',
    total_loans_count: 2,
    active_loans_count: 1,
    overdue_count: 0,
  },
  {
    id: 102,
    customer_code: 'CUST-SK-002',
    full_name: 'Sunil Verma',
    phone: '9820223344',
    address: 'Corner Stall, Central Bazaar',
    city: 'Ahmedabad',
    customer_type: 'SHOPKEEPER',
    shop_name: 'Verma Mobile Repair & Accessories',
    status: 'ACTIVE',
    registration_date: '2026-02-01',
    total_loans_count: 1,
    active_loans_count: 1,
    overdue_count: 1,
  },
  {
    id: 103,
    customer_code: 'CUST-CC-001',
    full_name: 'Meena Devi',
    phone: '9820334455',
    address: 'Flat 302, Gokul Heights, Civil Hospital Rd',
    city: 'Ahmedabad',
    customer_type: 'COMMON_CUSTOMER',
    occupation: 'Tailoring & Boutique Worker',
    status: 'ACTIVE',
    registration_date: '2026-01-15',
    total_loans_count: 2,
    active_loans_count: 1,
    overdue_count: 0,
  },
  {
    id: 104,
    customer_code: 'CUST-CC-002',
    full_name: 'Deepak Sharma',
    phone: '9820445566',
    address: 'House 56, Ward 4, Shanti Nagar',
    city: 'Ahmedabad',
    customer_type: 'COMMON_CUSTOMER',
    occupation: 'Factory Supervisor',
    status: 'ACTIVE',
    registration_date: '2026-03-01',
    total_loans_count: 1,
    active_loans_count: 1,
    overdue_count: 2,
  },
  {
    id: 105,
    customer_code: 'CUST-SK-003',
    full_name: 'Gopal Krishna',
    phone: '9820556677',
    address: 'Shop 8, Station Road Vegetable Market',
    city: 'Ahmedabad',
    customer_type: 'SHOPKEEPER',
    shop_name: 'Radhe Krishna Veg & Fruits',
    status: 'ACTIVE',
    registration_date: '2025-11-20',
    total_loans_count: 3,
    active_loans_count: 0,
    overdue_count: 0,
  },
];

const todayStr = new Date().toISOString().slice(0, 10);

export const initialLoans: Loan[] = [
  {
    id: 501,
    loan_number: 'LN-2026-SK001',
    customer_id: 101,
    customer_name: 'Ramesh Patel',
    customer_phone: '9820112233',
    customer_type: 'SHOPKEEPER',
    shop_name: 'Patel Provision & Kirana Store',
    product_id: 2,
    product_name: 'Daily Loan - Shopkeepers',
    principal_amount: 25000,
    contracted_income_amount: 2000,
    total_repayment_amount: 27000,
    total_installments: 25,
    repayment_frequency: 'DAILY',
    status: 'ACTIVE',
    application_date: '2026-08-15',
    disbursement_date: '2026-08-16',
    maturity_date: '2026-09-15',
    total_paid: 16200,
    total_principal_recovered: 15000,
    total_income_collected: 1200,
    outstanding_amount: 10800,
    installments: [
      { id: 1, loan_id: 501, loan_number: 'LN-2026-SK001', installment_number: 14, due_date: todayStr, scheduled_amount: 1080, principal_component: 1000, income_component: 80, paid_amount: 0, outstanding_amount: 1080, status: 'PENDING' },
      { id: 2, loan_id: 501, loan_number: 'LN-2026-SK001', installment_number: 15, due_date: '2026-09-11', scheduled_amount: 1080, principal_component: 1000, income_component: 80, paid_amount: 0, outstanding_amount: 1080, status: 'PENDING' },
      { id: 3, loan_id: 501, loan_number: 'LN-2026-SK001', installment_number: 16, due_date: '2026-09-12', scheduled_amount: 1080, principal_component: 1000, income_component: 80, paid_amount: 0, outstanding_amount: 1080, status: 'PENDING' },
    ],
  },
  {
    id: 502,
    loan_number: 'LN-2026-SK002',
    customer_id: 102,
    customer_name: 'Sunil Verma',
    customer_phone: '9820223344',
    customer_type: 'SHOPKEEPER',
    shop_name: 'Verma Mobile Repair & Accessories',
    product_id: 2,
    product_name: 'Daily Loan - Shopkeepers',
    principal_amount: 20000,
    contracted_income_amount: 2000,
    total_repayment_amount: 22000,
    total_installments: 25,
    repayment_frequency: 'DAILY',
    status: 'OVERDUE',
    application_date: '2026-08-10',
    disbursement_date: '2026-08-11',
    maturity_date: '2026-09-10',
    total_paid: 10560,
    total_principal_recovered: 9600,
    total_income_collected: 960,
    outstanding_amount: 11440,
    installments: [
      { id: 4, loan_id: 502, loan_number: 'LN-2026-SK002', installment_number: 12, due_date: '2026-09-08', scheduled_amount: 880, principal_component: 800, income_component: 80, paid_amount: 0, outstanding_amount: 880, status: 'OVERDUE' },
      { id: 5, loan_id: 502, loan_number: 'LN-2026-SK002', installment_number: 13, due_date: '2026-09-09', scheduled_amount: 880, principal_component: 800, income_component: 80, paid_amount: 0, outstanding_amount: 880, status: 'OVERDUE' },
      { id: 6, loan_id: 502, loan_number: 'LN-2026-SK002', installment_number: 14, due_date: todayStr, scheduled_amount: 880, principal_component: 800, income_component: 80, paid_amount: 0, outstanding_amount: 880, status: 'PENDING' },
    ],
  },
  {
    id: 503,
    loan_number: 'LN-2026-CC001',
    customer_id: 103,
    customer_name: 'Meena Devi',
    customer_phone: '9820334455',
    customer_type: 'COMMON_CUSTOMER',
    product_id: 1,
    product_name: 'Weekly Loan - Common Customers',
    principal_amount: 20000,
    contracted_income_amount: 4000,
    total_repayment_amount: 24000,
    total_installments: 10,
    repayment_frequency: 'WEEKLY',
    status: 'ACTIVE',
    application_date: '2026-07-20',
    disbursement_date: '2026-07-21',
    maturity_date: '2026-09-29',
    total_paid: 16800,
    total_principal_recovered: 14000,
    total_income_collected: 2800,
    outstanding_amount: 7200,
    installments: [
      { id: 7, loan_id: 503, loan_number: 'LN-2026-CC001', installment_number: 8, due_date: todayStr, scheduled_amount: 2400, principal_component: 2000, income_component: 400, paid_amount: 0, outstanding_amount: 2400, status: 'PENDING' },
      { id: 8, loan_id: 503, loan_number: 'LN-2026-CC001', installment_number: 9, due_date: '2026-09-17', scheduled_amount: 2400, principal_component: 2000, income_component: 400, paid_amount: 0, outstanding_amount: 2400, status: 'PENDING' },
      { id: 9, loan_id: 503, loan_number: 'LN-2026-CC001', installment_number: 10, due_date: '2026-09-24', scheduled_amount: 2400, principal_component: 2000, income_component: 400, paid_amount: 0, outstanding_amount: 2400, status: 'PENDING' },
    ],
  },
  {
    id: 504,
    loan_number: 'LN-2026-CC002',
    customer_id: 104,
    customer_name: 'Deepak Sharma',
    customer_phone: '9820445566',
    customer_type: 'COMMON_CUSTOMER',
    product_id: 1,
    product_name: 'Weekly Loan - Common Customers',
    principal_amount: 15000,
    contracted_income_amount: 3000,
    total_repayment_amount: 18000,
    total_installments: 10,
    repayment_frequency: 'WEEKLY',
    status: 'OVERDUE',
    application_date: '2026-07-05',
    disbursement_date: '2026-07-06',
    maturity_date: '2026-09-14',
    total_paid: 7200,
    total_principal_recovered: 6000,
    total_income_collected: 1200,
    outstanding_amount: 10800,
    installments: [
      { id: 10, loan_id: 504, loan_number: 'LN-2026-CC002', installment_number: 5, due_date: '2026-08-25', scheduled_amount: 1800, principal_component: 1500, income_component: 300, paid_amount: 0, outstanding_amount: 1800, status: 'OVERDUE' },
      { id: 11, loan_id: 504, loan_number: 'LN-2026-CC002', installment_number: 6, due_date: '2026-09-01', scheduled_amount: 1800, principal_component: 1500, income_component: 300, paid_amount: 0, outstanding_amount: 1800, status: 'OVERDUE' },
      { id: 12, loan_id: 504, loan_number: 'LN-2026-CC002', installment_number: 7, due_date: todayStr, scheduled_amount: 1800, principal_component: 1500, income_component: 300, paid_amount: 0, outstanding_amount: 1800, status: 'PENDING' },
    ],
  },
];

export const initialPayments: Payment[] = [
  {
    id: 901,
    payment_number: 'PAY-2026-0091',
    customer_id: 101,
    customer_name: 'Ramesh Patel',
    customer_type: 'SHOPKEEPER',
    shop_name: 'Patel Provision & Kirana Store',
    loan_id: 501,
    loan_number: 'LN-2026-SK001',
    payment_date: '2026-09-09 11:30:00',
    amount: 1080,
    payment_method: 'CASH',
    collector_name: 'Vikram Singh',
    status: 'COMPLETED',
    principal_recovered: 1000,
    income_collected: 80,
  },
  {
    id: 902,
    payment_number: 'PAY-2026-0092',
    customer_id: 103,
    customer_name: 'Meena Devi',
    customer_type: 'COMMON_CUSTOMER',
    loan_id: 503,
    loan_number: 'LN-2026-CC001',
    payment_date: '2026-09-03 14:15:00',
    amount: 2400,
    payment_method: 'UPI',
    reference_number: 'UPI983748291039',
    collector_name: 'Vikram Singh',
    status: 'COMPLETED',
    principal_recovered: 2000,
    income_collected: 400,
  },
];

export const initialFundTransactions: FundTransaction[] = [
  {
    id: 801,
    transaction_number: 'TX-CAP-001',
    fund_account_id: 2,
    account_name: 'Primary Business Current Account',
    transaction_date: '2026-01-01 10:00:00',
    transaction_type: 'CAPITAL_IN',
    direction: 'IN',
    amount: 500000,
    description: 'Initial Business Equity Capital Infusion',
    created_by_name: 'Rajesh Kumar',
  },
  {
    id: 802,
    transaction_number: 'TX-DISB-501',
    fund_account_id: 1,
    account_name: 'Main Cash Wallet (Physical Field Cash)',
    transaction_date: '2026-08-16 11:00:00',
    transaction_type: 'LOAN_DISBURSEMENT',
    direction: 'OUT',
    amount: 25000,
    description: 'Disbursed Loan LN-2026-SK001 to Ramesh Patel',
    reference_type: 'LOAN',
    reference_id: 501,
    created_by_name: 'Priya Sharma',
  },
  {
    id: 803,
    transaction_number: 'TX-REC-901',
    fund_account_id: 1,
    account_name: 'Main Cash Wallet (Physical Field Cash)',
    transaction_date: '2026-09-09 11:30:00',
    transaction_type: 'PRINCIPAL_COLLECTION',
    direction: 'IN',
    amount: 1000,
    description: 'Principal Recovery recycled into cash pool from LN-2026-SK001',
    reference_type: 'PAYMENT',
    reference_id: 901,
    created_by_name: 'Vikram Singh',
  },
  {
    id: 804,
    transaction_number: 'TX-INC-901',
    fund_account_id: 1,
    account_name: 'Main Cash Wallet (Physical Field Cash)',
    transaction_date: '2026-09-09 11:30:00',
    transaction_type: 'LENDING_INCOME',
    direction: 'IN',
    amount: 80,
    description: 'Lending Contract Income earned on LN-2026-SK001',
    reference_type: 'PAYMENT',
    reference_id: 901,
    created_by_name: 'Vikram Singh',
  },
  {
    id: 805,
    transaction_number: 'TX-EXP-001',
    fund_account_id: 1,
    account_name: 'Main Cash Wallet (Physical Field Cash)',
    transaction_date: '2026-09-05 17:00:00',
    transaction_type: 'EXPENSE',
    direction: 'OUT',
    amount: 3200,
    description: 'Field transit fuel & vehicle maintenance for collectors',
    created_by_name: 'Vikram Singh',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 701,
    expense_number: 'EXP-2026-001',
    category_name: 'COLLECTION_TRANSPORT',
    fund_account_id: 1,
    account_name: 'Main Cash Wallet (Physical Field Cash)',
    amount: 3200,
    expense_date: '2026-09-05',
    description: 'Field transit fuel and vehicle maintenance for collectors',
    status: 'PAID',
  },
  {
    id: 702,
    expense_number: 'EXP-2026-002',
    category_name: 'OFFICE_RENT',
    fund_account_id: 2,
    account_name: 'Primary Business Current Account',
    amount: 18000,
    expense_date: '2026-09-01',
    description: 'Branch Office Monthly Rent',
    status: 'PAID',
  },
];

export const initialEligibility: LoanEligibility[] = [
  {
    id: 601,
    customer_id: 105,
    customer_name: 'Gopal Krishna',
    status: 'ELIGIBLE',
    eligible_amount: 50000,
    reason: 'Settled 3 consecutive daily loans with 100% on-time repayment. High fund circulation turnover.',
    on_time_rate: 100,
    completed_loans_count: 3,
    overdue_incidents: 0,
    evaluated_at: '2026-09-01',
  },
  {
    id: 602,
    customer_id: 101,
    customer_name: 'Ramesh Patel',
    status: 'ELIGIBLE',
    eligible_amount: 35000,
    reason: 'Existing loan over 60% recovered with zero missed installments. Eligible for repeat advance upon closure.',
    on_time_rate: 98,
    completed_loans_count: 1,
    overdue_incidents: 0,
    evaluated_at: '2026-09-05',
  },
  {
    id: 603,
    customer_id: 104,
    customer_name: 'Deepak Sharma',
    status: 'NOT_ELIGIBLE',
    eligible_amount: 0,
    reason: '2 consecutive weekly installments overdue (>14 days). New loan creation blocked until overdue cleared.',
    on_time_rate: 62,
    completed_loans_count: 0,
    overdue_incidents: 3,
    evaluated_at: '2026-09-08',
  },
];

export const initialReconciliations: Reconciliation[] = [
  {
    id: 401,
    fund_account_id: 1,
    account_name: 'Main Cash Wallet (Physical Field Cash)',
    reconciliation_date: '2026-09-09',
    system_cash: 145000,
    actual_cash: 145000,
    discrepancy: 0,
    status: 'BALANCED',
    reconciled_by: 'Vikram Singh',
    notes: 'Evening cash drawer closing balanced with collector receipts.',
  },
];
