import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '../../../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  header: {
    marginBottom: 16,
  },
  welcomeText: {
    fontSize: 12,
    color: Colors.gray200,
    fontWeight: '600',
    fontFamily: Fonts.gilroy.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  userName: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.gray800,
    marginTop: 2,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  gridItem: {
    width: '48.5%',
  },
  card: {
    backgroundColor: Colors.backgroundContainer, // Gray card #F3F4F6
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.lightGray400, // #E5E7EB
    marginBottom: 16,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '800',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.gray800,
  },
  progressPercentage: {
    fontSize: 15,
    fontWeight: '800',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.primary,
  },
  barBackground: {
    height: 10,
    backgroundColor: Colors.lightGray400,
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 8,
  },
  barFill: {
    height: '100%',
    backgroundColor: Colors.primary,
    borderRadius: 5,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressLabelLeft: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.primary,
  },
  progressLabelRight: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: Fonts.gilroy.medium,
    color: Colors.gray200,
  },
  progressNote: {
    fontSize: 11,
    fontFamily: Fonts.gilroy.regular,
    color: Colors.gray200,
    lineHeight: 16,
  },
  activeLoanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  activeLoanTag: {
    fontSize: 10,
    fontWeight: '800',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.gray200,
    letterSpacing: 0.8,
  },
  activeLoanNumber: {
    fontSize: 18,
    fontWeight: '800',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.gray800,
    marginTop: 2,
  },
  statusBadge: {
    backgroundColor: Colors.purpleTintLightest,
    borderWidth: 1,
    borderColor: Colors.purpleBorderLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.primary,
  },
  activeLoanDetails: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  detailKey: {
    fontSize: 12,
    fontFamily: Fonts.gilroy.medium,
    color: Colors.gray200,
  },
  detailVal: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: Fonts.gilroy.semiBold,
    color: Colors.gray800,
  },
  scheduleActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    gap: 6,
  },
  scheduleActionBtnText: {
    fontSize: 13,
    fontWeight: '700',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.primary,
  },
  quickGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  quickBtn: {
    flex: 1,
    backgroundColor: Colors.backgroundContainer, // Gray card #F3F4F6
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  quickIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.lightGray400,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  quickBtnTitle: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: Fonts.gilroy.bold,
    color: Colors.gray800,
    marginBottom: 4,
  },
  quickBtnSub: {
    fontSize: 11,
    fontFamily: Fonts.gilroy.regular,
    color: Colors.gray200,
  },
});
